### ISSUE TITLE
Dodanie informacji i próba realizacji 

### ISSUE THREAD

**Issue by sebkaz** [zuzann18/Praca-Magisterska#1]
Korzystając OpenCV chciałbym aby to rozpoznawanie odbywało się zarówno na plikach jak i na widoku z kamery.

**Comment by zuzann18** [comment]
Postaram się, mam pytanie co do moich założeń co do zbioru - czy ilość 19 zbiorów dla danego rozmiaru  litery np. 28x28, będzie wystarczająca ?

**Comment by zuzann18** [comment]
dobrze
