### ISSUE TITLE
przygotowanie pliku z pracą 

### ISSUE THREAD

**Issue by sebkaz** [zuzann18/Praca-Magisterska#2]
spis tresci i przygotowanie info jakich plików ma dotyczyc zadanie. czy to co Pani tworzy 8x8 pixeli ma sluzyc do gerenrowania modelu ? i gdzie będą znajdowały się wszystie zbiory (bo rozumeim ze bedzie ich bardzo duzo)

**Comment by zuzann18** [comment]
Dzień dobry, zbiory będą znajdowały w  folderze dataset, Na podstawie pilików o matrycy np. 8 x 8 pikseli, a zwłaszcza 28 x 28, zamierzam nauczyć model rozpoznawać litery
